# Generated by Django 4.0 on 2024-05-31 04:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of the broker', max_length=255, verbose_name='Broker Name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('serialno', models.CharField(help_text='Enter the serial number', max_length=100, unique=True, verbose_name='Serial Number')),
                ('username', models.CharField(help_text='Enter the username', max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(help_text='Enter the email address', max_length=254, unique=True, verbose_name='Email')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Enter the WhatsApp number', max_length=15, null=True, verbose_name='WhatsApp Number')),
                ('server_id', models.CharField(blank=True, help_text='Enter the server ID', max_length=255, null=True, verbose_name='Server ID')),
                ('date_of_registration', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of user registration', verbose_name='Date of Registration')),
                ('date_of_expiry', models.DateTimeField(blank=True, help_text='Date and time of user expiry', null=True, verbose_name='Date of Expiry')),
                ('lot_size', models.IntegerField(default=0, help_text='Enter the lot size', verbose_name='Lot Size')),
                ('plain_password', models.CharField(blank=True, help_text='Enter the plain text password', max_length=128, null=True, verbose_name='Plain Password')),
                ('token', models.TextField(help_text='Enter the token (more than 300 characters)', verbose_name='Token')),
                ('platform', models.CharField(help_text='Enter the platform', max_length=255, verbose_name='Platform')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user is active', verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can access the admin site', verbose_name='Staff Status')),
                ('broker', models.ForeignKey(blank=True, help_text='Select the broker', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.broker', verbose_name='Broker')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to='users.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_users', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
