# Generated by Django 4.0 on 2024-06-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_superuser_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the lot size', max_digits=10, verbose_name='Lot Size'),
        ),
    ]
