# Generated by Django 4.0 on 2024-06-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_lot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True, help_text='Enter the token (more than 300 characters)', null=True, verbose_name='Token'),
        ),
    ]
