# Generated by Django 4.0 on 2024-06-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this broker is active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter the email address', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
