# Generated by Django 4.0 on 2024-06-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_broker_is_active_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, help_text='Enter the account name', max_length=255, null=True, verbose_name='Account Name'),
        ),
    ]
