# Generated by Django 4.0 on 2024-06-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_groups_user_is_superuser_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], help_text='Enter the transaction type (BUY or SELL)', max_length=4, verbose_name='Transaction Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', help_text='Enter the status of the transaction', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of transaction creation', verbose_name='Created At')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time of last modification', verbose_name='Modified On')),
                ('client_id', models.CharField(blank=True, help_text='Enter the unique ID', max_length=255, unique=True, verbose_name='Client ID')),
                ('stop_loss', models.DecimalField(decimal_places=2, help_text='Enter the stop loss value', max_digits=10, verbose_name='Stop Loss')),
                ('target', models.DecimalField(decimal_places=2, help_text='Enter the target value', max_digits=10, verbose_name='Target')),
                ('open_price', models.DecimalField(decimal_places=2, help_text='Enter the open price', max_digits=10, verbose_name='Open Price')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to='users.user', verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_transactions', to='users.user', verbose_name='Modified By')),
                ('user', models.ForeignKey(help_text='User who owns this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user', verbose_name='User')),
            ],
        ),
    ]
