# Generated by Django 4.0 on 2024-06-21 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_account_name'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('CLOSE', 'Close')], help_text='Enter the transaction type (BUY or SELL)', max_length=10, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user', verbose_name='User'),
        ),
    ]
